name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish-release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v6

      - name: Install Node and NPM
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install and build
        run: npm ci

      - name: Publish Release (Windows)
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish -- --platform=win32

      - name: Publish Release (macOS)
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish -- --platform=darwin --arch=arm64,x64
